# Generated by Django 3.2 on 2022-05-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_product_reviews_review_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('order_id', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('address', models.TextField()),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
