# Generated by Django 3.2 on 2022-05-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='long_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.product'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
