# Generated by Django 3.2 on 2022-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20220505_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 2), ('DELIVERED', 1), ('ORDERED', 3)], max_length=255, null=True),
        ),
    ]
