# Generated by Django 3.2 on 2022-05-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderedProduct', to='website.product'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[(3, 'ORDERED'), (1, 'DELIVERED'), (2, 'CANCELLED')], max_length=255, null=True),
        ),
    ]
