# Generated by Django 3.2 on 2022-05-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_orderdetail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='capacity',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
    ]
