# Generated by Django 3.2 on 2022-05-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20220505_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('ORDERED', 'ORDERED'), ('DELIVERED', 'DELIVERED')], max_length=255, null=True),
        ),
    ]
