# Generated by Django 3.2 on 2022-05-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_orderdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='short_description',
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
