# Generated by Django 3.2 on 2022-05-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20220505_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
    ]
