# Generated by Django 3.2 on 2022-05-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_orderdetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('about', models.TextField()),
                ('vision', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('ORDERED', 'ORDERED'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
    ]
