# Generated by Django 3.2 on 2022-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20220506_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='vision_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='vision',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
    ]
