# Generated by Django 3.2 on 2022-05-06 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20220506_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='apartment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='free_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='shipping_charge',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('INCART', 'INCART'), ('CANCELLED', 'CANCELLED'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
    ]
