# Generated by Django 3.2 on 2022-05-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20220506_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='current_location',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='transit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('INCART', 'INCART'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
    ]
