# Generated by Django 3.2 on 2022-05-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20220506_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waterless',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('waterless', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('INCART', 'INCART'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED')], max_length=255, null=True),
        ),
    ]
