# Generated by Django 4.0.4 on 2022-05-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20220507_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='transit',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('ORDERED', 'ORDERED'), ('INCART', 'INCART')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitPoint', to='website.orderdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
