# Generated by Django 4.0.4 on 2022-05-07 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_remove_orderdetail_transit_alter_orderdetail_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycheckpoint',
            name='transit_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('INCART', 'INCART'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
    ]
