# Generated by Django 4.0.4 on 2022-05-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_deliverycheckpoint_transit_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='tracking_number',
            field=models.CharField(default=123456789, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('INCART', 'INCART'), ('ORDERED', 'ORDERED'), ('DELIVERED', 'DELIVERED')], max_length=255, null=True),
        ),
    ]
