# Generated by Django 3.2 on 2022-05-08 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0020_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('DELIVERED', 'DELIVERED'), ('INCART', 'INCART'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
    ]
