# Generated by Django 4.0.4 on 2022-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_product_price_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('INCART', 'INCART'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
    ]
