# Generated by Django 4.0.4 on 2022-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_product_price_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('ORDERED', 'ORDERED'), ('INCART', 'INCART'), ('DELIVERED', 'DELIVERED')], max_length=255, null=True),
        ),
    ]
