# Generated by Django 4.0.4 on 2022-05-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('INCART', 'INCART')], max_length=255, null=True),
        ),
    ]
