# Generated by Django 4.0.4 on 2022-05-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_orderdetail_status_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('INCART', 'INCART'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='static/images'),
        ),
    ]
