# Generated by Django 4.0.4 on 2022-05-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_product_price_alter_orderdetail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='200ml', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('INCART', 'INCART'), ('ORDERED', 'ORDERED'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
    ]
