# Generated by Django 4.0.4 on 2022-05-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_remove_orderdetail_size_product_size_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('INCART', 'INCART'), ('ORDERED', 'ORDERED'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED')], max_length=255, null=True),
        ),
    ]
