# Generated by Django 4.0.4 on 2022-05-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='PUBLISHED', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('DELIVERED', 'DELIVERED'), ('INCART', 'INCART'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
    ]
