# Generated by Django 4.0.4 on 2022-05-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_product_status_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='payment_methof',
            field=models.CharField(default='GPay', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('INCART', 'INCART'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
    ]
