# Generated by Django 4.0.4 on 2022-05-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_alter_orderdetail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='payment_methof',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('INCART', 'INCART'), ('DELIVERED', 'DELIVERED'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
    ]
