# Generated by Django 4.0.4 on 2022-05-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_rename_payment_methof_orderdetail_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='channel',
            field=models.CharField(default='Delhivery', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'ORDERED'), ('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('INCART', 'INCART')], max_length=255, null=True),
        ),
    ]
