# Generated by Django 3.2 on 2022-05-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_auto_20220514_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerbanner',
            name='image',
            field=models.FileField(upload_to='static/images/offers'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('DELIVERED', 'DELIVERED'), ('INCART', 'INCART'), ('INTRANSIT', 'INTRANSIT'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
    ]
