# Generated by Django 3.2 on 2022-06-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20220514_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerbanner',
            name='image',
            field=models.FileField(upload_to='website/static/images/offers'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('ORDERED', 'ORDERED'), ('DELIVERED', 'DELIVERED'), ('INTRANSIT', 'INTRANSIT'), ('INCART', 'INCART')], max_length=255, null=True),
        ),
    ]
