# Generated by Django 3.2 on 2022-06-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_auto_20220605_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('WISHLIST', 'WISHLIST'), ('DELIVERED', 'DELIVERED'), ('INTRANSIT', 'INTRANSIT'), ('INCART', 'INCART'), ('ORDERED', 'ORDERED'), ('CANCELLED', 'CANCELLED')], max_length=255, null=True),
        ),
    ]
