# Generated by Django 3.2 on 2022-06-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('INTRANSIT', 'INTRANSIT'), ('WISHLIST', 'WISHLIST'), ('DELIVERED', 'DELIVERED'), ('ORDERED', 'ORDERED'), ('CANCELLED', 'CANCELLED'), ('INCART', 'INCART')], max_length=255, null=True),
        ),
    ]
