# Generated by Django 3.2 on 2022-06-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_auto_20220607_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('WISHLIST', 'WISHLIST'), ('DELIVERED', 'DELIVERED'), ('INCART', 'INCART'), ('INTRANSIT', 'INTRANSIT'), ('CANCELLED', 'CANCELLED'), ('ORDERED', 'ORDERED')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, default='India', max_length=255, null=True),
        ),
    ]
