# Generated by Django 3.2 on 2022-06-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_auto_20220607_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('INCART', 'INCART'), ('DELIVERED', 'DELIVERED'), ('WISHLIST', 'WISHLIST'), ('ORDERED', 'ORDERED'), ('INTRANSIT', 'INTRANSIT')], max_length=255, null=True),
        ),
    ]
